version: '3'

services:
  internet-toggle:
    build: .
    container_name: internet-toggle
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - INTERNET_IP=${INTERNET_IP:-8.8.8.8}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-60}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - KASA_PLUG_IP=${KASA_PLUG_IP}
      - AUDIT_MODE=${AUDIT_MODE:-False}
      - PYTHONUNBUFFERED=1  # This ensures Python output is unbuffered
    volumes:
      - ./:/app
    network_mode: host  # Required for proper ping functionality
    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep stdin open